# Generated by Django 5.1.7 on 2025-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_entry_song_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("is_favorite", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="entry",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
